#!/bin/sh
TESTFILE=${TMPDIR:-/tmp}/scrub-testfile.$$
rm -f $TESTFILE
./pad 512k $TESTFILE || exit 1
$PATH_SCRUB -r -p old $TESTFILE 2>&1 | sed -e "s!$TESTFILE!file!" >t06.out || exit 1
diff t06.exp t06.out >t06.diff
rc=$?
rm -f $TESTFILE
exit $rc
