#!/bin/sh

# This is a special test to be run on the author's test systems.

TEST=`basename $0 | cut -d- -f1`
# Test requires root
test `id -u` = 0 || exit 77

EXPFILE=${TEST}-`hostname`.exp
TESTDEV=/dev/scrub-testdisk
test -f $EXPFILE || exit 77
if ! test -b $TESTDEV && ! test -c $TESTDEV; then
    echo $TESTDEV is unavailable >&2
    exit 77
fi
$PATH_SCRUB -T $TESTDEV >${TEST}.out 2>&1 || exit 1
diff $EXPFILE ${TEST}.out >${TEST}.diff
