#!/bin/sh

# This is a special test to be run on the author's test systems.

TEST=`basename $0 | cut -d- -f1`
# Test requires root
test `id -u` == 0 || exit 77

EXPFILE=${TEST}-`hostname`.exp
test -f $EXPFILE || exit 77

case `hostname` in
    manbearpig)
        ./tgetsize /dev/rhdisk0 >t10.out 2>&1
        ;;
    cartman)
        ./tgetsize /dev/sda1 >t10.out 2>&1
        ./tgetsize /dev/mapper/VolGroup00-LogVol00 >>t10.out 2>&1
        ;;
    jimmy)
        ./tgetsize /dev/rdsk/c1t0d0s0 >t10.out 2>&1
        ;;
    timmy)
        ./tgetsize /dev/rdsk/c1t0d0s0 >t10.out 2>&1
        ;;
    marklar)
        ./tgetsize /dev/rdisk1s3 >t10.out 2>&1
        ;;
esac
diff $EXPFILE $TEST.out >$TEST.diff
