#!/bin/sh
TEST=`basename $0 | cut -d- -f1`
TESTFILE=${TMPDIR:-/tmp}/scrub-testfile.$$
rm -f $TESTFILE
./pad 512k $TESTFILE || exit 1

od -c $TESTFILE >$TEST.out || exit 1

$PATH_SCRUB --dry-run -p fillff $TESTFILE 2>&1 \
		| sed -e "/res fork/d" \
		| sed -e "s!${TESTFILE}!file!" 2>&1 >>$TEST.out|| exit 1

od -c $TESTFILE >>$TEST.out || exit 1

unlink $TESTFILE || exit 1
# -b is needed b/c od spacing is different on OS/X (issue 31)
diff -b $TEST.exp $TEST.out >$TEST.diff
