#!/bin/sh
TEST=`basename $0 | cut -d- -f1`
# Test requires root
test `id -u` == 0 || exit 77

TESTDIR=`mktemp -d` || exit 1
mount -t tmpfs -o size=32m scrubtest $TESTDIR || exit 77

$PATH_SCRUB -s 1m -X $TESTDIR/foo 2>&1 \
	| sed -e "s!${TESTDIR}!testdir!" 2>&1 >$TEST.out
echo "scrub exited with rc=$?" >>$TEST.out

umount $TESTDIR
rmdir $TESTDIR

diff $TEST.exp $TEST.out >$TEST.diff
