#!/bin/sh
TEST=`basename $0 | cut -d- -f1`
TMPLATE="${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"
TESTDIR=`mktemp -d $TMPLATE` || exit 1

./pad 512k $TESTDIR/a || exit 1
./pad 512k $TESTDIR/b || exit 1
./pad 512k $TESTDIR/c || exit 1

echo Created 3 files >$TEST.out

$PATH_SCRUB $TESTDIR/* $TESTDIR/nonexistent 2>&1 \
	| sed -e "s!${TESTDIR}!testdir!" >>$TEST.out

rm -r $TESTDIR

diff $TEST.exp $TEST.out >$TEST.diff
